// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
)

type Message struct {
	ID        int32         `json:"id"`
	SessionID sql.NullInt32 `json:"session_id"`
	Sender    string        `json:"sender"`
	Content   string        `json:"content"`
	Timestamp sql.NullTime  `json:"timestamp"`
}

type Session struct {
	ID        int32         `json:"id"`
	UserID    sql.NullInt32 `json:"user_id"`
	StartedAt sql.NullTime  `json:"started_at"`
	EndedAt   sql.NullTime  `json:"ended_at"`
}

type Summary struct {
	ID                int32          `json:"id"`
	SessionID         int32          `json:"session_id"`
	FullSummary       sql.NullString `json:"full_summary"`
	CompressedSummary sql.NullString `json:"compressed_summary"`
	CreatedAt         sql.NullTime   `json:"created_at"`
}

type User struct {
	ID             int32        `json:"id"`
	Email          string       `json:"email"`
	HashedPassword string       `json:"hashed_password"`
	StudentStatus  sql.NullBool `json:"student_status"`
	CreatedAt      sql.NullTime `json:"created_at"`
}
