name: mental_health_companion
description: A virtual AI psychologist for students

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  intl: ^0.20.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  assets:
    - assets/