openapi: 3.0.0
info:
  title: Mental Health Companion API
  version: 1.0.0
  description: RESTful API for AI therapy sessions, user authentication, and session history.

servers:
  - url: http://localhost:8080

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Successful registration
        '400':
          description: Invalid input

  /auth/login:
    post:
      summary: Log in a user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: JWT token issued
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Unauthorized

  /session/start:
    get:
      summary: Start a new therapy session
      tags: [Session]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Session started successfully
          content:
            application/json:
              schema:
                type: integer
                example: 42

  /session/end:
    post:
      summary: End the current session
      tags: [Session]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndSessionRequest'
      responses:
        '200':
          description: Session ended and saved
        '400':
          description: Invalid session data

  /message:
    post:
      summary: Send a message to AI
      tags: [Chat]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
      responses:
        '200':
          description: AI reply returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'

  /sessions:
    get:
      summary: Get all previous session summaries
      tags: [Session]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Array of session summaries
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AuthRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required: [email, password]

    AuthResponse:
      type: object
      properties:
        token:
          type: string

    MessageRequest:
      type: object
      properties:
        message:
          type: string
      required: [message]

    MessageResponse:
      type: object
      properties:
        reply:
          type: string

    EndSessionRequest:
      type: object
      properties:
        id:
          type: integer
        messages:
          type: array
          items:
            $ref: '#/components/schemas/ChatMessage'
      required: [id, messages]

    ChatMessage:
      type: object
      properties:
        sender:
          type: string
          enum: [user, ai]
        content:
          type: string
