services:
  mental-health-api:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    container_name: mental-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
